databases:
  - name: micronaut
    databaseName: micronaut_s9o9
    user: micronaut_s9o9_user

services:
  - type: web
    name: chatapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false